name: Build and Deploy
on:
  push:
    branches:
      - website
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v1
        with:
          persist-credentials: false
      - run: |
          echo "Actions"
          echo "Triggered"
      # - name: Install and Build 🔧
      #   run: |
      #     npm install
      #     npm run build
      # - name: Deploy 🚀
      #   uses: JamesIves/github-pages-deploy-action@releases/v3
      #   with:
      #     ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      #     BRANCH: gh-pages
      #     FOLDER: dist
